## aggregating functions

In [1]:
import numpy as np

In [2]:
vector = [1,2,3,4]


In [3]:
np.min(vector)

1

In [4]:
np.max(vector)

4

In [5]:
np.mean(vector)

2.5

In [6]:
np.median(vector)

2.5

In [7]:
vector

[1, 2, 3, 4]

## matrices

In [10]:
matrix = np.array([[1,2,3,4],[5,6,7,8]])

In [12]:
matrix.mean(axis=0)

array([2.5, 6.5])

In [13]:
matrix.mean(axis=1)

array([2.5, 6.5])

# broadcasting

In [14]:
arr_2= np.full((5,1),10)

In [15]:
arr_2

array([[10],
       [10],
       [10],
       [10],
       [10]])

In [18]:
arr_2.ndim

2

In [20]:
arr_2 = np.full((5),10)
arr_2

array([10, 10, 10, 10, 10])

In [21]:
arr_2 = np.full(5,10)
arr_2

array([10, 10, 10, 10, 10])

In [22]:
arr_2.shape

(5,)

In [23]:
np.shape(10)

()

In [26]:
### Understanding how broadcasting works, if needed to add a single value to a vector or matrix, use scalar value like 10.
arr_3=arr_2 + 5
arr_3

array([15, 15, 15, 15, 15])

In [27]:
arr_4 = arr_2 * 100
arr_4

array([1000, 1000, 1000, 1000, 1000])

In [28]:
#matrix example
arr_5 = np.full((5,1),10)
arr_5 = arr_5 *5
arr_5

array([[50],
       [50],
       [50],
       [50],
       [50]])

In [30]:
# how to broadcast array to another array
arr_6 = np.array([1,2,3,4,5])
arr_7 = np.array([[11,12,13,14,15],[16,17,18,19,20]])

In [34]:
arr_8= arr_7 + arr_6
arr_8

array([[12, 14, 16, 18, 20],
       [17, 19, 21, 23, 25]])

In [32]:
arr_9 = arr_6 * arr_7
arr_9

array([[ 11,  24,  39,  56,  75],
       [ 16,  34,  54,  76, 100]])

In [33]:
arr_10 = arr_7 / arr_6
arr_10

array([[11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ],
       [16.        ,  8.5       ,  6.        ,  4.75      ,  4.        ]])

# if same shape the stretching can be broadcasted to 2 arrays

In [37]:
arr_11 = np.array([1,2,3,4])
# add an extra axis to this vector to make it 4X1
arr_12= arr_11.copy()
arr_11 = arr_11[:,np.newaxis]
arr_11

array([[1],
       [2],
       [3],
       [4]])

In [38]:

arr_12

array([1, 2, 3, 4])

In [39]:
arr_13 = arr_11 +arr_12
arr_13

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

# Broadcasting is impossible if shapes don't match

In [41]:
# example 
a = np.array([1,2,3,4])
b= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [42]:
a,b

(array([1, 2, 3, 4]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

# both arrays above has diff shape as array a has 4 elements, when stretched will make 4 columns, b has only 3 columns.
# ValueError: operands could not be broadcast together with shapes (4,) (3,3) 

In [43]:
c= a+b

ValueError: operands could not be broadcast together with shapes (4,) (3,3) 

# docs for refernce
https://numpy.org/doc/stable/user/basics.broadcasting.htmlv