## Basic Array operations, arithmetic and logical operations 


In [ ]:
#addition, subtraction, multiplication and division

In [2]:
import numpy as np

In [3]:
arr1 = [1,2,3,4,5]
arr2 = [6,7,8,9,10]

arr1 = np.array(arr1)
arr2 = np.array(arr2)

In [7]:
arr3=arr1+arr2
arr3


array([ 7,  9, 11, 13, 15])

In [6]:
arr1,arr2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [8]:
arr1/arr2 #vector to vector division

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [9]:
arr1/10 #vector to scalar division

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [10]:
arr1+ 5

array([ 6,  7,  8,  9, 10])

In [11]:
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [12]:
arr1*2

array([ 2,  4,  6,  8, 10])

#Logical operations

In [14]:
arr1>2

array([False, False,  True,  True,  True])

In [15]:
arr1[arr1>2]

array([3, 4, 5])

## Any and all functions to check if condition is satisfied in array

In [16]:
np.any(arr2>6)

True

In [17]:
np.all(arr1>3)

False

## Finding insersection with logical and, T * T = T, F * T = F, F*F=F

In [18]:
arr4= (arr1>2)

In [19]:
arr4

array([False, False,  True,  True,  True])

In [26]:
arr5 = (arr2>9)

In [27]:
arr5

array([False, False, False, False,  True])

In [28]:
arr4 & arr5

array([False, False, False, False,  True])