## Learn Numpy from coursera , https://www.coursera.org/learn/numpy-and-pandas-basics-for-future-data-scientistsabs


In [1]:
lst1 = [1,2,3]
lst2=[4,5,6]
lst3=[7,8,9]


In [2]:
import numpy as np

In [3]:
arr = np.array([lst1,lst2,lst3])

In [4]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr[1] # first index row , 2nd row

array([4, 5, 6])

In [12]:
arr[0:2,0:3] # first row 0 to 3 index elements. The last index number is not considered.

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr[0,2:3]

array([3])

In [22]:
arr[0,2:3]=3

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##negative indexing

In [24]:
arr[-1]

array([7, 8, 9])

In [25]:
arr[-2]

array([4, 5, 6])

In [31]:
arr[2,-3]

7

## Understand copy concept

In [32]:
my_slice = arr[:,-1]
my_slice

array([3, 6, 9])

In [33]:
#if try and replace a value of any element in my_slice, it will change the value in actual array
my_slice[0]=1000
my_slice

array([1000,    6,    9])

In [34]:
arr

array([[   1,    2, 1000],
       [   4,    5,    6],
       [   7,    8,    9]])

In [35]:
#use .base to see actual array my-slice is part of. it will show the original array
my_slice.base

array([[   1,    2, 1000],
       [   4,    5,    6],
       [   7,    8,    9]])

In [36]:
my_slice[0]=3
my_slice

array([3, 6, 9])

In [38]:
my_slice.base

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
my_slice=arr[:,-1].copy()

In [42]:
my_slice[0]=999
my_slice

array([999,   6,   9])

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Indexing with logical operators 

In [44]:
arr>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [45]:
arr[arr>5]

array([6, 7, 8, 9])

In [46]:
##Winsorizing
arr[arr>5]=1000
arr

array([[   1,    2,    3],
       [   4,    5, 1000],
       [1000, 1000, 1000]])

In [60]:
(arr %2 > 0) & (arr > 2)

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])

In [61]:
##Complex composite conditions
condition = ((arr %2 > 0) & (arr > 2))
arr[condition]

array([3, 5])

In [ ]:
## The winsorizing creates a copy of array, the .base attribute won't return anything.
