## joining arrays

In [1]:
import numpy as np
np.random.seed(42)

In [2]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

In [4]:
arr3 = np.concatenate((arr1,arr2)) # note arrays are passed as tuple
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
#Horizontal and Vertical Stack
arr4 = np.hstack((arr1,arr2)) # same as concatenate
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
arr5 = np.vstack((arr1,arr2))
arr5

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
# Try 2X2 arraym
matrix_a = np.array([[1,2,3,4],[5,6,7,8]])
matrix_b= np.array([[11,12,13,14],[15,16,17,18]])

In [12]:
matrix_c = np.hstack((matrix_a,matrix_b))
matrix_c

array([[ 1,  2,  3,  4, 11, 12, 13, 14],
       [ 5,  6,  7,  8, 15, 16, 17, 18]])

In [13]:
matrix_c = np.vstack((matrix_a,matrix_b))
matrix_c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [15]:
## Concatenate matrices

matrix_d = np.concatenate((matrix_a,matrix_b)) # by default axis=0, vertically
matrix_d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [16]:

matrix_d = np.concatenate((matrix_a,matrix_b), axis=-1) # axis=-1, horizontally
matrix_d

array([[ 1,  2,  3,  4, 11, 12, 13, 14],
       [ 5,  6,  7,  8, 15, 16, 17, 18]])

In [17]:
# To stack ,concatenate arrays one of the diemnsions should match, example, 
# if 1X2 is concatenated wit 1X1, they can only be concatenated at axis-0, row-wise