In [ ]:
#pip install numpy

In [2]:
import numpy as np

In [4]:
arr=np.array([1,2,3])
print(arr)
print(arr.shape)

[1 2 3]
(3,)


In [5]:
# 2 D array

twod=np.array([[2,3,4],[6,7,8],[5,5,5]])
print(twod)
print(twod.shape)

[[2 3 4]
 [6 7 8]
 [5 5 5]]
(3, 3)


In [8]:
#Get dimension of the arrays created above
print(" a is of dim :",arr.ndim)
print("b is of dim,",twod.ndim)

 a is of dim : 1
b is of dim, 2


In [10]:
#Data types
print(arr.dtype)
print(twod.dtype)

#specify type of int for array
c=np.array([1,2,3],dtype="int16")
print(c)
print(c.dtype)

int64
int64
[1 2 3]
int16


In [15]:
#number of elements
print(arr.size)
print(twod.size)

##byte size of each element, depends on data type. int64 , each element is of 8 bytes
print(arr.itemsize,arr.dtype)

3
9
8 int64


In [16]:
#size of numpy array
print(arr.nbytes) # same as arr.itemsize * arr.size
print(arr.itemsize * arr.size)
print(c.nbytes)

24
24
6


In [17]:
aa=np.array([[1,2,3],[4,5,6]])
print(aa)

[[1 2 3]
 [4 5 6]]


In [18]:
print(aa[1,1])

5


In [19]:
bb= np.array([4,6,8])
print(bb/2)

[2. 3. 4.]


In [25]:
y=0.6
d="yes" if y>=0.5 else "no"
print(d)

yes


In [26]:
a=[1.,2.,3.,4.]
b=[0.1,0.01,0.001,0.0001]
a=np.array(a)
b=np.array(b)
print(a)
print(b)
c=a+b
print(c)

[1. 2. 3. 4.]
[0.1    0.01   0.001  0.0001]
[1.1    2.01   3.001  4.0001]


In [6]:
shape = (3,5)
my_arr=np.zeros(shape)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
my_arr = np.full(shape,2)
my_arr

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [ ]:
my_arr.dtype

In [11]:
## add 5 random nan values in array
my_arr=my_arr.astype(float)
my_arr[1,1]=np.nan
my_arr[2,3]=np.nan
my_arr[2,1]=np.nan
my_arr[0,3]=np.nan
my_arr

array([[ 2.,  2.,  2., nan,  2.],
       [ 2., nan,  2.,  2.,  2.],
       [ 2., nan,  2., nan,  2.]])

In [13]:
np.isnan(my_arr)

array([[False, False, False,  True, False],
       [False,  True, False, False, False],
       [False,  True, False,  True, False]])

In [15]:
np.array(np.where(np.isnan(my_arr)))

array([[0, 1, 2, 2],
       [3, 1, 1, 3]])

In [16]:
my_arr

array([[ 2.,  2.,  2., nan,  2.],
       [ 2., nan,  2.,  2.,  2.],
       [ 2., nan,  2., nan,  2.]])

In [17]:
my_arr[np.isnan(my_arr)]=1000
my_arr

array([[   2.,    2.,    2., 1000.,    2.],
       [   2., 1000.,    2.,    2.,    2.],
       [   2., 1000.,    2., 1000.,    2.]])