# Module 1 Challenges

In [2]:
import numpy as np

## Challenge 01
### 1.1 Create a NumPy array [1 point]

* Create a 1-dimensional NumPy array with values `1`, `2`, `3`, and `4`.
* Save it the variable `my_array`.
* Check that it has the correct value.

In [2]:
my_array = None

# YOUR CODE HERE
try:
    my_array= np.array([1,2,3,4])
except:
    raise NotImplementedError()
my_array

array([1, 2, 3, 4])

In [3]:
# Hidden tests are within this cell

## Challenge 02
### 2.1 Create array with values as rows [1 point]

Create a **3x4** NumPy array with the values from ``list1``, ``list2``, and ``list3`` as the rows.
1. Save it to the variable ``task_two_array``.
2. Pick out the value at row `2`, column `3` and save it to the variable ``task_two_value``.
3. Pick out the third row and save it to the variable ``task_two_row``.

In [4]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]
list3 = [9, 10, 11, 12]

In [5]:
task_two_array = None
task_two_value = None
task_two_row = None

# YOUR CODE HERE
try:
    task_two_array = np.array([list1,list2,list3])
    task_two_value = task_two_array[1,2]
    task_two_row = task_two_array[2]
except:
    raise NotImplementedError()
task_two_value, task_two_array, task_two_row

(np.int64(7),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([ 9, 10, 11, 12]))

In [6]:
# Hidden tests are within this cell

### 2.2 Create array with values as columns [1 point]

Create a **`4`x`3`** NumPy array with the values from `list1`, `list2`, and `list3` as the columns.
1. Save it to the variable `task_three_array`.
2. Pick out the value at row `2`, column `3` and save it to the variable `task_three_value`.
3. Pick out the third row and save it to the variable `task_three_row`.

In [7]:
task_three_array = None
task_three_value = None
task_three_row = None

# YOUR CODE HERE
task_three_array = np.array([list1,list2,list3]).T
task_three_value = task_three_array[1,2]
task_three_row = task_three_array[2]
#raise NotImplementedError()
task_three_value, task_three_array,task_three_row

(np.int64(10),
 array([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]]),
 array([ 3,  7, 11]))

In [8]:
# Hidden tests are within this cell

### 2.3 Create column array with specific value [1 point]

Create a **`3`x`5`** NumPy array with all values set to `2`. Save it to the variable `task_four_array`.

In [9]:
shape=(3,5)
task_four_array = np.full(shape,2)
task_four_array
# YOUR CODE HERE
#raise NotImplementedError()

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [10]:
# Hidden tests are within this cell

### 2.4 Consider array datatypes [1 point]

Consider the following NumPy arrays.
1. Do the objects `array1` and `array2` have the same datatype? Assign your answer as a `bool` to the
   variable `mcq_1`.
2. Do the items in `array1` and `array2` have the same type? Assign your answer as a `bool` to the
   variable `mcq_2`.
3. Is the first element of `array3` an integer? Assign your answer as a `bool` to the variable `mcq_3`.

In [11]:
array1 = np.array([1, 2, 3])
array2 = np.array([1.0, 2.0, 3.0])
array3 = np.array([1, 2, 3.0])

print(array1.dtype)
print(array2.dtype)
mcq_1 = (type(array1) == type(array2))
print(mcq_1)

mcq_2= (array1.dtype == array2.dtype)
print(mcq_2)

mcq_3 = (array3.dtype == 'int')
print(mcq_3)

# YOUR CODE HERE
#raise NotImplementedError()

int64
float64
True
False
False


In [12]:
# Hidden tests are within this cell

### 2.5 Extract data from an array [1 point]

Select the middle `3` rows and the middle `3` columns of `rand_array`. Save them to the variable `middle_array`.


In [13]:
np.random.seed(4242)
rand_array = np.random.randint(1, 100, size=(5, 7))

In [14]:
shape=rand_array.shape

middle_array = rand_array[1:4,2:5]
middle_array 
#rand_array
# YOUR CODE HERE
#raise NotImplementedError()

array([[41, 73, 94],
       [67, 33, 92],
       [20, 65, 49]])

In [15]:
# Hidden tests are within this cell

### 2.6 Extract data from an array [1 point]

Select the middle `3` rows (and all columns) of `rand_array`. Save them to the variable `middle_rows`.


In [16]:
middle_rows = rand_array[1:4,]
middle_rows
# YOUR CODE HERE
#raise NotImplementedError()

array([[20, 94, 41, 73, 94, 43, 14],
       [37, 53, 67, 33, 92, 60, 26],
       [48, 25, 20, 65, 49, 97, 43]])

In [17]:
# Hidden tests are within this cell

### 2.7 Extract data from an array [1 point]

Select the middle `3` columns (and all rows) of `rand_array`. Save them to the variable `middle_columns`.


In [18]:
middle_columns = rand_array[:,2:5]
middle_columns
# YOUR CODE HERE
#raise NotImplementedError()

array([[18, 55, 35],
       [41, 73, 94],
       [67, 33, 92],
       [20, 65, 49],
       [22,  1, 42]])

In [19]:
# Hidden tests are within this cell

### 2.8 Create array [1 point]

Make a **`3`x`3`** NumPy array with the values `1`, `2`, `3` on the diagonal, and 0s everywhere
else. Save it to the variable `task_nine_array`.

In [20]:
task_nine_array = np.diag([1,2,3])
task_nine_array
# YOUR CODE HERE
#raise NotImplementedError()

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [21]:
# Hidden tests are within this cell

### 2.9 Create array with nulls [1 point]

Make a **`3`x`3`** NumPy array with the values `1`, `2`, `3` on the diagonal and null values
everywhere else. Save it to the variable `task_ten_array`.

Hint: if you create the array with integer values, you will need to convert it to a `float` to add
`np.nan` values.

In [22]:
task_ten_array = np.full((3,3),np.nan)
np.fill_diagonal(task_ten_array,[1,2,3])
task_ten_array
# YOUR CODE HERE
#raise NotImplementedError()

array([[ 1., nan, nan],
       [nan,  2., nan],
       [nan, nan,  3.]])

In [23]:
# Hidden tests are within this cell

## Challenge 03
### 3.1 Locating indices for null values [1 point]

In the first cell below we have created an array with null values in five random locations.

Find the indices of the `np.nan` values in `rand_array`. Save them to the variable `nan_indices`.
`nan_indices` should have shape `(5, 2)`. Each row should contain the row and column index of a
`np.nan` value.

In [3]:
np.random.seed(4242)
rand_array = np.random.randint(1, 100, size=(5, 7))

# Set five random values in rand_array to np.nan
indices = np.random.choice(range(rand_array.size), size=5, replace=False)
rand_array = rand_array.astype(float)
rand_array.ravel()[indices] = np.nan


In [4]:
nan_indices = None
nan_indices=np.array(np.where(np.isnan(rand_array)))
nan_indices
# YOUR CODE HERE
#raise NotImplementedError()

array([[0, 1, 2, 3, 4],
       [4, 1, 3, 6, 1]])

In [5]:
# Hidden tests are within this cell

### 3.2 Replace missing data [1 point]

Replace the missing indices in `rand_array` with the value `1000`. Save the result to the variable
`filled_array`.

In [6]:
filled_array = None
rand_array[np.isnan(rand_array)]=1000
filled_array = rand_array
filled_array
# YOUR CODE HERE
#raise NotImplementedError()

array([[  47.,   14.,   18.,   55., 1000.,   81.,   18.],
       [  20., 1000.,   41.,   73.,   94.,   43.,   14.],
       [  37.,   53.,   67., 1000.,   92.,   60.,   26.],
       [  48.,   25.,   20.,   65.,   49.,   97., 1000.],
       [  21., 1000.,   22.,    1.,   42.,   63.,   98.]])

In [7]:
# Hidden tests are within this cell

## Challenge 04

Consider the following **`3`x`3`** NumPy arrays named `array1` and `array2`.

In [29]:
array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

array2 = np.array([[13, 14, 15, 16],
                   [17, 18, 19, 20],
                   [21, 22, 23, 24]])

### 4.1 Sum arrays [1 point]

Add up the two arrays **element-wise** and save the result to the variable `sum_array`.


In [30]:
sum_array = None
sum_array = array1 + array2
sum_array
# YOUR CODE HERE
#raise NotImplementedError()

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [31]:
# Hidden tests are within this cell

### 4.2 Sum vectors [1 point]

Below is code that attempts to add up the values in two one-dimensional vectors. The result should
be `[6, 8, 10, 12]`. However, the current code __does not__ produce the correct result. Apply the
OILER framework to help you diagnose and resolve the issue.

In [34]:
array1 = [1, 2, 3, 4]
array2 = [5, 6, 7, 8]

array3 = np.array(array1) + np.array(array2)
array3

# YOUR CODE HERE
#raise NotImplementedError()

array([ 6,  8, 10, 12])

In [35]:
# Hidden tests are within this cell