#sorting_arrays

In [1]:
import numpy as np
np.random.seed(42)

In [6]:
rand_arr = np.random.randint(10,size=10)
rand_arr

array([8, 0, 9, 2, 6, 3, 8, 2, 4, 2])

In [7]:
rand_arr.sort() ## Without making copy, inplace

In [8]:
rand_arr ## sorted array

array([1, 1, 3, 4, 6, 6, 8, 8, 8, 9])

In [9]:
## using numpy sort to create a copy of orginal array
arr2 = np.random.randint(10,size=10)
arr3 = np.sort(arr2) ## sorts inb ascending order
arr3

array([0, 1, 1, 2, 3, 3, 4, 6, 7, 9])

In [13]:
## to sort in descending order we need to use np.flip on already sorted array
arr4=np.flip(arr3)
arr4


array([9, 7, 6, 4, 3, 3, 2, 1, 1, 0])

In [14]:
arr2

array([9, 4, 1, 3, 6, 7, 2, 0, 3, 1])

In [15]:
arr5= np.flip(arr2)  # on unsorted array, it just reverses the elements
arr5

array([1, 3, 0, 2, 7, 6, 3, 1, 4, 9])

In [16]:
## reverse array using slicing
arr2

array([9, 4, 1, 3, 6, 7, 2, 0, 3, 1])

In [20]:
arr2_reverse = arr2[::-1]

In [21]:
arr2_reverse

array([1, 3, 0, 2, 7, 6, 3, 1, 4, 9])

## Sorting matrices

In [24]:
matrix_a = np.random.randint(10,size=(4,4))
matrix_a

array([[7, 3, 1, 5],
       [5, 9, 3, 5],
       [1, 9, 1, 9],
       [3, 7, 6, 8]])

In [25]:
matrix_b= np.sort(matrix_a) ## row wise sorting
matrix_b

array([[1, 3, 5, 7],
       [3, 5, 5, 9],
       [1, 1, 9, 9],
       [3, 6, 7, 8]])

In [28]:
matrix_c = np.sort(matrix_a,axis=0)
matrix_c

array([[1, 3, 1, 5],
       [3, 7, 1, 5],
       [5, 9, 3, 8],
       [7, 9, 6, 9]])